
-- Insert ingredients data into site_content table
INSERT INTO site_content (key, value, type) VALUES
('ingredients_title', 'Pure, Natural Ingredients', 'text'),
('ingredients_subtitle', 'Every jar is crafted with carefully selected, premium ingredients that work synergistically to provide superior healing and nourishment for your skin.', 'text'),
('ingredient_1_name', 'CBD Isolate', 'text'),
('ingredient_1_benefit', 'Anti-inflammatory & pain relief', 'text'),
('ingredient_1_description', 'Pure CBD for optimal healing and comfort', 'text'),
('ingredient_1_icon', 'pill', 'text'),
('ingredient_2_name', 'Blue Dream Terpenes', 'text'),
('ingredient_2_benefit', 'Aromatherapy & relaxation', 'text'),
('ingredient_2_description', 'Signature blend for soothing experience', 'text'),
('ingredient_2_icon', 'leaf', 'text'),
('ingredient_3_name', 'Mango Butter', 'text'),
('ingredient_3_benefit', 'Deep moisturization', 'text'),
('ingredient_3_description', 'Rich vitamins A, C, and E for skin regeneration', 'text'),
('ingredient_3_icon', 'droplet', 'text'),
('ingredient_4_name', 'Avocado Oil', 'text'),
('ingredient_4_benefit', 'Penetrating hydration', 'text'),
('ingredient_4_description', 'Omega-rich oil that absorbs quickly', 'text'),
('ingredient_4_icon', 'heart', 'text'),
('ingredient_5_name', 'Shea Butter', 'text'),
('ingredient_5_benefit', 'Protective barrier', 'text'),
('ingredient_5_description', 'Natural healing with anti-inflammatory properties', 'text'),
('ingredient_5_icon', 'shield', 'text'),
('ingredient_6_name', 'Coconut Oil', 'text'),
('ingredient_6_benefit', 'Antimicrobial protection', 'text'),
('ingredient_6_description', 'Natural antibacterial and antifungal properties', 'text'),
('ingredient_6_icon', 'zap', 'text'),
('testimonial_1_name', 'Sarah Chen', 'text'),
('testimonial_1_role', 'Tattoo Artist', 'text'),
('testimonial_1_image', 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=80&h=80&fit=crop&crop=face', 'image'),
('testimonial_1_content', 'Blue Dream Budder has revolutionized how my clients heal. The natural ingredients work incredibly well, and the CBD provides amazing anti-inflammatory benefits.', 'text'),
('testimonial_1_rating', '5', 'text'),
('testimonial_2_name', 'Marcus Rodriguez', 'text'),
('testimonial_2_role', 'Client', 'text'),
('testimonial_2_image', 'https://images.unsplash.com/photo-1721322800607-8c38375eef04?w=80&h=80&fit=crop&crop=face', 'image'),
('testimonial_2_content', 'After trying countless aftercare products, this is the only one that actually helped my tattoo heal without irritation. The Blue Dream terpenes are genius!', 'text'),
('testimonial_2_rating', '5', 'text'),
('testimonial_3_name', 'Emily Turner', 'text'),
('testimonial_3_role', 'Skin Care Enthusiast', 'text'),
('testimonial_3_image', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=80&h=80&fit=crop&crop=face', 'image'),
('testimonial_3_content', 'I use this even when I don''t have fresh ink. The mango and shea butter combination leaves my skin so soft and nourished. Premium quality!', 'text'),
('testimonial_3_rating', '5', 'text');
