// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vozstxchkgpxzetwdzow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvenN0eGNoa2dweHpldHdkem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDQyMjAsImV4cCI6MjA2Njc4MDIyMH0.Ti9dIcVzMY_jNzvbPHPz9n47f8p3xrmrT_mAMb5yG6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);